Домашнее задание 8 (ClassLoader)
Guha5277/innopolis-course pull request #4
Opened 2020-12-04 16:59 UTC by Guha5277

Выполнил задание в соответствии с требуемыми условиями:

1. Программа запускается (класс Main) и ожидает пользовательский ввод (класс View);
2. Ввод продолжается до тех пор, пока не будет получена пустая строка;
3. Полученные данные от пользователя передаются в CodeCompiler, который в свою очередь:
- Передаёт в SourceMaker код полученный от пользователя. SourceMaker записывает код в SomeClass.java;
- Компилирует SomeClass.java в SomeClass.class;
- С помощью ClassLoader загружает полученный класс в программу и запускает метод doWork(); этого класса.

2020-12-09 20:29 UTC, svdovin requested changes

2020-12-09 20:29 UTC, svdovin commented on lesson08/src/main/java/task01/compiler/CodeCompiler.java
> +            declaredMethods[0].invoke(obj);
Предполагается, что вызов должен быть через интерфейс

2020-12-09 20:29 UTC, svdovin commented on lesson08/src/main/java/task01/compiler/SourceMaker.java
> +    private void writeSourceToDisk(String filePath, String sourceCode) {
запись есть, но после исполнения или перед закрытием программы было бы хорошо его еще и удалять (java и class)

2020-12-17 08:54 UTC, Guha5277 commented on lesson08/src/main/java/task01/compiler/CodeCompiler.java
> +            declaredMethods[0].invoke(obj);
Добавил интерфейс

2020-12-17 08:55 UTC, Guha5277 commented on lesson08/src/main/java/task01/compiler/SourceMaker.java
> +    private void writeSourceToDisk(String filePath, String sourceCode) {
Добавил удаление исходников и байт-кода по выходу из программы

2020-12-17 08:55 UTC, merged